/* Para evitar posibles problemas de pérdida de datos, debe revisar este script detalladamente antes de ejecutarlo fuera del contexto del diseñador de base de datos.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.EntidadDeSalud
	(
	NUMERO nvarchar(50) NOT NULL,
	INSTITUCION nvarchar(300) NULL,
	TIPO nvarchar(100) NULL,
	SUBTIPO nvarchar(100) NULL,
	NOMBRE_CENTRO nvarchar(200) NULL,
	NOMBRE_LOCALIDAD nvarchar(100) NULL,
	NOMBRE_MUNICIPIO nvarchar(100) NULL,
	NOMBRE_ESTADO nvarchar(100) NULL,
	LATITUD nvarchar(50) NULL,
	LONGITUD nvarchar(50) NULL,
	TELEFONO nvarchar(200) NULL,
	DOMICILIO nvarchar(500) NULL,
	HORARIO nvarchar(200) NULL
	)  ON [PRIMARY]
GO

--ALTER TABLE dbo.EntidadDeSalud ADD CONSTRAINT
--	PK_EntidadDeSalud PRIMARY KEY CLUSTERED 
--	(
--	NUMERO
--	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = ON, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

--GO

ALTER TABLE dbo.EntidadDeSalud SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
